[package]
name = "zbps"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
CommandLib = "1.0.0"
colored = "2.1.0"
crossterm = "0.27.0"
dirs = "5.0.1"
indicatif = "0.17.8"
sysinfo = "0.30.10"
